### ISSUE TITLE
FACT tool does not work properly

### ISSUE THREAD

**Issue by w0r1dhe110** [scriptingxss/EmbedOS#5]
hello sir：
The FACT tool in the virtual machine runs incorrectly, maybe the dependency is not installed completely。

```
> sudo ./start_all_installed_fact_components 
[2020-07-25 00:02:41][start_all_installed_fact_components][INFO]: starting db
[2020-07-25 00:02:42][MongoMgr][INFO]: start local mongo database
[2020-07-25 00:02:43][start_all_installed_fact_components][INFO]: starting frontend
[2020-07-25 00:02:43][start_all_installed_fact_components][INFO]: starting backend
Traceback (most recent call last):
  File "/home/embedos/tools/FACT_core/src/../start_fact_backend", line 25, in <module>
    from analysis.PluginBase import PluginInitException
  File "/home/embedos/tools/FACT_core/src/analysis/PluginBase.py", line 10, in <module>
    from objects.file import FileObject
  File "/home/embedos/tools/FACT_core/src/objects/file.py", line 7, in <module>
    from helperFunctions.hash import get_sha256
  File "/home/embedos/tools/FACT_core/src/helperFunctions/hash.py", line 6, in <module>
    import tlsh
ModuleNotFoundError: No module named 'tlsh'
```

**Comment by scriptingxss** [comment]
Correct. In the readme it states
Firmware Analysis Comparison Toolkit (FACT) : Not fully installed. More disk space required.

You'll have to expand the virtual hard disk at least another 10-20GB of space. See the FACT repo for more details https://github.com/fkie-cad/FACT_core
